import React from 'react';

import { ContainerTechnologies, TechLinks } from '../styles';

export default function Techs() {
  return (
    <ContainerTechnologies>
      <a
        className="slideAnimation"
        href="https://www.linux.org/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/linux/linux-original.svg"
          alt="linux"
        />
      </a>{' '}
      <a
        className="slideAnimation"
        href="https://www.nginx.com"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/nginx/nginx-original.svg"
          alt="nginx"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.docker.com/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/docker/docker-original-wordmark.svg"
          alt="docker"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://git-scm.com/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://www.vectorlogo.zone/logos/git-scm/git-scm-icon.svg"
          alt="git"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.w3.org/html/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original-wordmark.svg"
          alt="html5"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.w3schools.com/css/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/css3/css3-original-wordmark.svg"
          alt="css3"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://sass-lang.com"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/sass/sass-original.svg"
          alt="sass"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.gnu.org/software/bash/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/bootstrap/bootstrap-plain-wordmark.svg"
          alt="bootstrap"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://developer.mozilla.org/en-US/docs/Web/JavaScript"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-original.svg"
          alt="javascript"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://nodejs.org"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/nodejs/nodejs-original-wordmark.svg"
          alt="nodejs"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://expressjs.com"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/express/express-original-wordmark.svg"
          alt="express"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.typescriptlang.org/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/typescript/typescript-original.svg"
          alt="typescript"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://reactjs.org/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/react/react-original-wordmark.svg"
          alt="react"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://redux.js.org"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/redux/redux-original.svg"
          alt="redux"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.electronjs.org"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/electron/electron-original.svg"
          alt="electron"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.mysql.com/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/mysql/mysql-original-wordmark.svg"
          alt="mysql"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.sqlite.org/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://www.vectorlogo.zone/logos/sqlite/sqlite-icon.svg"
          alt="sqlite"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.mongodb.com/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/mongodb/mongodb-original-wordmark.svg"
          alt="mongodb"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://firebase.google.com/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://www.vectorlogo.zone/logos/firebase/firebase-icon.svg"
          alt="firebase"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.linux.org/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/linux/linux-original.svg"
          alt="linux"
        />
      </a>{' '}
      <a
        className="slideAnimation"
        href="https://www.nginx.com"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/nginx/nginx-original.svg"
          alt="nginx"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.docker.com/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/docker/docker-original-wordmark.svg"
          alt="docker"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://git-scm.com/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://www.vectorlogo.zone/logos/git-scm/git-scm-icon.svg"
          alt="git"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.w3.org/html/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original-wordmark.svg"
          alt="html5"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.w3schools.com/css/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/css3/css3-original-wordmark.svg"
          alt="css3"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://sass-lang.com"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/sass/sass-original.svg"
          alt="sass"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.gnu.org/software/bash/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/bootstrap/bootstrap-plain-wordmark.svg"
          alt="bootstrap"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://developer.mozilla.org/en-US/docs/Web/JavaScript"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-original.svg"
          alt="javascript"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://nodejs.org"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/nodejs/nodejs-original-wordmark.svg"
          alt="nodejs"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://expressjs.com"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/express/express-original-wordmark.svg"
          alt="express"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.typescriptlang.org/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/typescript/typescript-original.svg"
          alt="typescript"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://reactjs.org/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/react/react-original-wordmark.svg"
          alt="react"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://redux.js.org"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/redux/redux-original.svg"
          alt="redux"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.electronjs.org"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/electron/electron-original.svg"
          alt="electron"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.mysql.com/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/mysql/mysql-original-wordmark.svg"
          alt="mysql"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.sqlite.org/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://www.vectorlogo.zone/logos/sqlite/sqlite-icon.svg"
          alt="sqlite"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.mongodb.com/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/mongodb/mongodb-original-wordmark.svg"
          alt="mongodb"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://firebase.google.com/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://www.vectorlogo.zone/logos/firebase/firebase-icon.svg"
          alt="firebase"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.linux.org/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/linux/linux-original.svg"
          alt="linux"
        />
      </a>{' '}
      <a
        className="slideAnimation"
        href="https://www.nginx.com"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/nginx/nginx-original.svg"
          alt="nginx"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.docker.com/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/docker/docker-original-wordmark.svg"
          alt="docker"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://git-scm.com/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://www.vectorlogo.zone/logos/git-scm/git-scm-icon.svg"
          alt="git"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.w3.org/html/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original-wordmark.svg"
          alt="html5"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.w3schools.com/css/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/css3/css3-original-wordmark.svg"
          alt="css3"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://sass-lang.com"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/sass/sass-original.svg"
          alt="sass"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.gnu.org/software/bash/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/bootstrap/bootstrap-plain-wordmark.svg"
          alt="bootstrap"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://developer.mozilla.org/en-US/docs/Web/JavaScript"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-original.svg"
          alt="javascript"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://nodejs.org"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/nodejs/nodejs-original-wordmark.svg"
          alt="nodejs"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://expressjs.com"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/express/express-original-wordmark.svg"
          alt="express"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.typescriptlang.org/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/typescript/typescript-original.svg"
          alt="typescript"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://reactjs.org/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/react/react-original-wordmark.svg"
          alt="react"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://redux.js.org"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/redux/redux-original.svg"
          alt="redux"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.electronjs.org"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/electron/electron-original.svg"
          alt="electron"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.mysql.com/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/mysql/mysql-original-wordmark.svg"
          alt="mysql"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.sqlite.org/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://www.vectorlogo.zone/logos/sqlite/sqlite-icon.svg"
          alt="sqlite"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.mongodb.com/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/mongodb/mongodb-original-wordmark.svg"
          alt="mongodb"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://firebase.google.com/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://www.vectorlogo.zone/logos/firebase/firebase-icon.svg"
          alt="firebase"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.linux.org/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/linux/linux-original.svg"
          alt="linux"
        />
      </a>{' '}
      <a
        className="slideAnimation"
        href="https://www.nginx.com"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/nginx/nginx-original.svg"
          alt="nginx"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.docker.com/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/docker/docker-original-wordmark.svg"
          alt="docker"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://git-scm.com/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://www.vectorlogo.zone/logos/git-scm/git-scm-icon.svg"
          alt="git"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.w3.org/html/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original-wordmark.svg"
          alt="html5"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.w3schools.com/css/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/css3/css3-original-wordmark.svg"
          alt="css3"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://sass-lang.com"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/sass/sass-original.svg"
          alt="sass"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.gnu.org/software/bash/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/bootstrap/bootstrap-plain-wordmark.svg"
          alt="bootstrap"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://developer.mozilla.org/en-US/docs/Web/JavaScript"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-original.svg"
          alt="javascript"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://nodejs.org"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/nodejs/nodejs-original-wordmark.svg"
          alt="nodejs"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://expressjs.com"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/express/express-original-wordmark.svg"
          alt="express"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.typescriptlang.org/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/typescript/typescript-original.svg"
          alt="typescript"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://reactjs.org/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/react/react-original-wordmark.svg"
          alt="react"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://redux.js.org"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/redux/redux-original.svg"
          alt="redux"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.electronjs.org"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/electron/electron-original.svg"
          alt="electron"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.mysql.com/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/mysql/mysql-original-wordmark.svg"
          alt="mysql"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.sqlite.org/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://www.vectorlogo.zone/logos/sqlite/sqlite-icon.svg"
          alt="sqlite"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.mongodb.com/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/mongodb/mongodb-original-wordmark.svg"
          alt="mongodb"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://firebase.google.com/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://www.vectorlogo.zone/logos/firebase/firebase-icon.svg"
          alt="firebase"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.linux.org/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/linux/linux-original.svg"
          alt="linux"
        />
      </a>{' '}
      <a
        className="slideAnimation"
        href="https://www.nginx.com"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/nginx/nginx-original.svg"
          alt="nginx"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.docker.com/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/docker/docker-original-wordmark.svg"
          alt="docker"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://git-scm.com/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://www.vectorlogo.zone/logos/git-scm/git-scm-icon.svg"
          alt="git"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.w3.org/html/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original-wordmark.svg"
          alt="html5"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.w3schools.com/css/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/css3/css3-original-wordmark.svg"
          alt="css3"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://sass-lang.com"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/sass/sass-original.svg"
          alt="sass"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.gnu.org/software/bash/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/bootstrap/bootstrap-plain-wordmark.svg"
          alt="bootstrap"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://developer.mozilla.org/en-US/docs/Web/JavaScript"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-original.svg"
          alt="javascript"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://nodejs.org"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/nodejs/nodejs-original-wordmark.svg"
          alt="nodejs"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://expressjs.com"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/express/express-original-wordmark.svg"
          alt="express"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.typescriptlang.org/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/typescript/typescript-original.svg"
          alt="typescript"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://reactjs.org/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/react/react-original-wordmark.svg"
          alt="react"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://redux.js.org"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/redux/redux-original.svg"
          alt="redux"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.electronjs.org"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/electron/electron-original.svg"
          alt="electron"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.mysql.com/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/mysql/mysql-original-wordmark.svg"
          alt="mysql"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.sqlite.org/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://www.vectorlogo.zone/logos/sqlite/sqlite-icon.svg"
          alt="sqlite"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.mongodb.com/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/mongodb/mongodb-original-wordmark.svg"
          alt="mongodb"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://firebase.google.com/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://www.vectorlogo.zone/logos/firebase/firebase-icon.svg"
          alt="firebase"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.linux.org/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/linux/linux-original.svg"
          alt="linux"
        />
      </a>{' '}
      <a
        className="slideAnimation"
        href="https://www.nginx.com"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/nginx/nginx-original.svg"
          alt="nginx"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.docker.com/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/docker/docker-original-wordmark.svg"
          alt="docker"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://git-scm.com/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://www.vectorlogo.zone/logos/git-scm/git-scm-icon.svg"
          alt="git"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.w3.org/html/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original-wordmark.svg"
          alt="html5"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.w3schools.com/css/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/css3/css3-original-wordmark.svg"
          alt="css3"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://sass-lang.com"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/sass/sass-original.svg"
          alt="sass"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.gnu.org/software/bash/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/bootstrap/bootstrap-plain-wordmark.svg"
          alt="bootstrap"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://developer.mozilla.org/en-US/docs/Web/JavaScript"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-original.svg"
          alt="javascript"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://nodejs.org"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/nodejs/nodejs-original-wordmark.svg"
          alt="nodejs"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://expressjs.com"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/express/express-original-wordmark.svg"
          alt="express"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.typescriptlang.org/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/typescript/typescript-original.svg"
          alt="typescript"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://reactjs.org/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/react/react-original-wordmark.svg"
          alt="react"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://redux.js.org"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/redux/redux-original.svg"
          alt="redux"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.electronjs.org"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/electron/electron-original.svg"
          alt="electron"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.mysql.com/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/mysql/mysql-original-wordmark.svg"
          alt="mysql"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.sqlite.org/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://www.vectorlogo.zone/logos/sqlite/sqlite-icon.svg"
          alt="sqlite"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.mongodb.com/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/mongodb/mongodb-original-wordmark.svg"
          alt="mongodb"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://firebase.google.com/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://www.vectorlogo.zone/logos/firebase/firebase-icon.svg"
          alt="firebase"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.linux.org/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/linux/linux-original.svg"
          alt="linux"
        />
      </a>{' '}
      <a
        className="slideAnimation"
        href="https://www.nginx.com"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/nginx/nginx-original.svg"
          alt="nginx"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.docker.com/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/docker/docker-original-wordmark.svg"
          alt="docker"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://git-scm.com/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://www.vectorlogo.zone/logos/git-scm/git-scm-icon.svg"
          alt="git"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.w3.org/html/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original-wordmark.svg"
          alt="html5"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.w3schools.com/css/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/css3/css3-original-wordmark.svg"
          alt="css3"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://sass-lang.com"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/sass/sass-original.svg"
          alt="sass"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.gnu.org/software/bash/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/bootstrap/bootstrap-plain-wordmark.svg"
          alt="bootstrap"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://developer.mozilla.org/en-US/docs/Web/JavaScript"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-original.svg"
          alt="javascript"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://nodejs.org"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/nodejs/nodejs-original-wordmark.svg"
          alt="nodejs"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://expressjs.com"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/express/express-original-wordmark.svg"
          alt="express"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.typescriptlang.org/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/typescript/typescript-original.svg"
          alt="typescript"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://reactjs.org/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/react/react-original-wordmark.svg"
          alt="react"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://redux.js.org"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/redux/redux-original.svg"
          alt="redux"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.electronjs.org"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/electron/electron-original.svg"
          alt="electron"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.mysql.com/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/mysql/mysql-original-wordmark.svg"
          alt="mysql"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.sqlite.org/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://www.vectorlogo.zone/logos/sqlite/sqlite-icon.svg"
          alt="sqlite"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.mongodb.com/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/mongodb/mongodb-original-wordmark.svg"
          alt="mongodb"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://firebase.google.com/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://www.vectorlogo.zone/logos/firebase/firebase-icon.svg"
          alt="firebase"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.linux.org/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/linux/linux-original.svg"
          alt="linux"
        />
      </a>{' '}
      <a
        className="slideAnimation"
        href="https://www.nginx.com"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/nginx/nginx-original.svg"
          alt="nginx"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.docker.com/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/docker/docker-original-wordmark.svg"
          alt="docker"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://git-scm.com/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://www.vectorlogo.zone/logos/git-scm/git-scm-icon.svg"
          alt="git"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.w3.org/html/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original-wordmark.svg"
          alt="html5"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.w3schools.com/css/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/css3/css3-original-wordmark.svg"
          alt="css3"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://sass-lang.com"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/sass/sass-original.svg"
          alt="sass"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.gnu.org/software/bash/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/bootstrap/bootstrap-plain-wordmark.svg"
          alt="bootstrap"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://developer.mozilla.org/en-US/docs/Web/JavaScript"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-original.svg"
          alt="javascript"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://nodejs.org"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/nodejs/nodejs-original-wordmark.svg"
          alt="nodejs"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://expressjs.com"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/express/express-original-wordmark.svg"
          alt="express"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.typescriptlang.org/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/typescript/typescript-original.svg"
          alt="typescript"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://reactjs.org/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/react/react-original-wordmark.svg"
          alt="react"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://redux.js.org"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/redux/redux-original.svg"
          alt="redux"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.electronjs.org"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/electron/electron-original.svg"
          alt="electron"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.mysql.com/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/mysql/mysql-original-wordmark.svg"
          alt="mysql"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.sqlite.org/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://www.vectorlogo.zone/logos/sqlite/sqlite-icon.svg"
          alt="sqlite"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://www.mongodb.com/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/mongodb/mongodb-original-wordmark.svg"
          alt="mongodb"
        />
      </a>
      <a
        className="slideAnimation"
        href="https://firebase.google.com/"
        target="_blank"
        rel="noreferrer"
      >
        <TechLinks
          className="slideAnimation"
          src="https://www.vectorlogo.zone/logos/firebase/firebase-icon.svg"
          alt="firebase"
        />
      </a>
    </ContainerTechnologies>
  );
}
