// EXAMPLE
export const BOTAO_SUCCESS = 'BOTAO_SUCCESS';
export const BOTAO_REQUEST = 'BOTAO_REQUEST';
export const BOTAO_FAILURE = 'BOTAO_FAILURE';

// AUTH
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

// AUTH
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

// AUTH
export const USER_EDIT_REQUEST = 'USER_EDIT_REQUEST';
export const USER_EDIT_SUCCESS = 'USER_EDIT_SUCCESS';
export const USER_EDIT_FAILURE = 'USER_EDIT_FAILURE';

export const PERSIST_REHYDRATE = 'persist/REHYDRATE';
